### PR TITLE
Handle Note type in tidal-parse

### LINKED ISSUE #725: Broken tests in tidal-parse
After merge of #708, tests on tidal-parse are failing, caused by introduction of the new `Note` datatype

### PR DESCRIPTION
**Pull request by ndr-brt**
Should fix #725 

Test are still broken but with an error like
`*** Failed! Exception: '<<loop>>' (after 1 test): | Exception thrown while showing test case: '<<loop>>' |`

Think it's something not bind to the `Note` newtype. 
@dktr0 can you help me about that?

### CODE REVIEW

File: tidal-parse/src/Sound/Tidal/Parse.hs [hunk 1]
```diff
@@ -708,6 +750,9 @@ instance Parse (Pattern Double -> (Pattern a -> Pattern a) -> Pattern a -> Patte
     $(fromTidal "someCyclesBy") <|>
     $(fromTidal "plyWith")
 
+instance Parse (Pattern T.Note -> (Pattern a -> Pattern a) -> Pattern a -> Pattern a) where
+  parser = parser
```
Comment (jwaldmann) [inline tidal-parse/src/Sound/Tidal/Parse.hs:754]: This looks strange, and may create the `<<loop>>` when called? Some `fmap T.Note` missing?

Comment (dktr0) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: Yeah, that's definitely infinite/empty recursion. If you have, for example an example of a function with that type you could do: parser = $(fromTidal "thatFunction")

Comment (ndr-brt) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: uhm... ok... and what if I haven't? at the moment only params "note", "midinote" and "up".
I tried also with `empty`, but, no luck

Comment (dktr0) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: If there's no way of making that type (Pattern Note -> (Pattern a -> Pattern a) -> Pattern a) in Tidal then you don't need to make a parser/Parse instance for it at all. I can comment more if you can give some examples of actual code you might want to parse.

Comment (jwaldmann) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: What exactly *is* the failing test here? (Is it visible in Travis, or how do I reproduce?)

Comment (ndr-brt) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: I have to tell you... I didn't need to parse anything, I was just trying to fix compilation errors and failing tests, but I'm not fully aware of the behavior of tidal-parse code, so any help would be appreciated :)

Comment (ndr-brt) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: @jwaldmann here's the errors, at the end of the log:
https://travis-ci.org/github/tidalcycles/Tidal/jobs/732245834

Comment (dktr0) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: I will look at this later this afternoon. Still it would help to have some examples of this Note stuff in action - being mentioned here is the first I've heard of any of this...

Comment (ndr-brt) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: Note is just a sort of alias of Double, born to solve this issue: https://github.com/tidalcycles/Tidal/issues/702

Comment (dktr0) [reply tidal-parse/src/Sound/Tidal/Parse.hs:754]: I see two places where you have parser = parser, which creates an infinite loop. If there is really no expression that evaluates to the types (at those places where you currently have parser = parser) then those instances/parsers (all of them) shouldn't be there at all; moreover, any pathways in other instances/parsers that reference those will also need to be deleted. I would expect it would "work" if both/all were defined as empty - perhaps you had defined one of them as empty and left the other in for the test?  Anyway, can I suggest that we start by removing pathways that don't correspond to any actual Tidal code - and then if it still causes problems, I'll look closer? (As the person usually maintaining this slightly complicated structure, I don't want to deal with the extra cognitive load of code that doesn't do anything!)

**Comment by jwaldmann** [comment]
> If there is really no expression that evaluates to the types 

well the test cases are precisely such expressions? 

I am looking into this. For later reference, here's how I reproduce (with ghc-8.10.2)
```
cabal run --allow-newer tidal-parse test
```
I am getting exactly the output that's in the travis log linked above, ending
```
Successes: 57, Pending: 0, Failures: 9
```

**Comment by dktr0** [comment]
@jwaldmann these are old tests that are failing - not tests that address expressions that don't exist... if there's no example of an expression for a given type then there's no parser that can be written for it, and no test of that parser that can be written. Meanwhile, parser = parser can certainly break existing tests.

**Comment by dktr0** [comment]
If we say that one of the ways a can be produced is by parsing (b -> a) and then applying b, yet the parser we provide for (b -> a) is infinitely recursive and there is no way of actually producing (b -> a) that will cause many tests involving parsing a to fail.

**Comment by ndr-brt** [comment]
@dktr0 woa, that was ees, I was wrong (and really silly) with `parser = parser`, changing that with `parser = empty` fixed everything.
Now we're ok!

**Comment by dktr0** [comment]
Great! I still think code paths that are empty should be deleted. I'll probably do it instinctively later if you don't do it now, anyway... ;)

**Comment by ndr-brt** [comment]
I did it by myself, removed all unused code parts, resolved also some compilation warnings. :)

**Comment by dktr0** [comment]
Awesome - thanks!

**Review by dktr0 — APPROVED** [review]

**Comment by yaxu** [comment]
Thanks a lot!
